### ISSUE TITLE
how to wrap the code in a jar?

### ISSUE THREAD

**Issue by lootoos** [chandra-prakash-reddy/DDOSDetector#1]
what methods of inverting into a jar so that it can be run via java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -jar ddos.jar?(JDK java 11)

**Comment by chandra-prakash-reddy** [comment]
you can just run below commands, make sure you are in directory where pom.xml exists which is root of your project

also go through prerequisite for this to run in readme.md 
1.```mvn clean install```
2.```java  -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -jar target/DDOSDetector-v-0.1.jar stream```
